---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pcf-repo
  type: git
  source:
    uri: https://github.com/ECSTeam/pcf-connect
    branch: master
    access_token: {{github_token}}

- name: slack
  type: slack-notification
  source:
    url: {{slack_webhook_url}}

jobs:
- name: test-pcf
  on_failure:
    <<: *notify_slack
  on_success:
    put: slack
    params:
      text: "`$BUILD_PIPELINE_NAME` build successful: $ATC_EXTERNAL_URL/builds/$BUILD_ID"
  plan:
  - get: pcf-repo
    trigger: true
  - task: test-pcf
    file: pcf-repo/ci/test-pcf.yml
    params:
      OPSMAN_HOST: {{opsman_host}}
      OPSMAN_USERNAME: {{opsman_username}}
      OPSMAN_PASSWORD: {{opsman_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}

notify_slack: &notify_slack
  put: slack
  params:
    text: "`$BUILD_PIPELINE_NAME` build failed for job `$BUILD_JOB_NAME`: $ATC_EXTERNAL_URL/builds/$BUILD_ID"
